[package]
name = "cryptopals-rust"
version = "0.1.0"
authors = ["Eugene Lim"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.30"
rand = "0.7.3"
regex = "1.3.9"
